### PR TITLE
Adding PHP 8 functions, PHPDocs, parameter/return types and creating …

### PR DESCRIPTION
**Pull request by guiiamorim**
…except method on InputHandler.

### CODE REVIEW

**Comment by guiiamorim** [comment]
Well, this is odd.. The tests passed on my machine, I'll see what went wrong later tonight.
image

**Comment by DeveloperMarius** [comment]
Hey,

wow I got no verification about your PR. 
The error is only on windows, wired. I will look into it^^

~ Marius

**Comment by DeveloperMarius** [comment]
I think it has something to do with your trait. Can you do some debugging?

**Comment by guiiamorim** [comment]
Hi @DeveloperMarius,

I'll do it tomorrow. I'm not being able to spend much time on any side projects lately but will try to give some attention to this project so we can continue improving this package

**Comment by DeveloperMarius** [comment]
Hey,

okay. I am also very busy. Just work on the project when you have time. I am doing the same^^

~ Marius

**Comment by aolko** [comment]
are you going to merge that?

**Comment by DeveloperMarius** [comment]
Hey,
I will do some changes to that later today and merge it.

~ Marius

**Comment by DeveloperMarius** [comment]
Hey,
I have done the cleanup in another branch. release will follow soon.
It would have been to much work to resolve the merge conflicts. Please open another PR, if you have additional cleanup.

~ Marius

**Pull request closed without merging**
