### PR TITLE
Let's talk about the feature of the simple-router

### PR DESCRIPTION
**Pull request by DeveloperMarius**
Hello everyone,

in this PR we will talk about the feature of the simple-php-router.
Puts your ideas and feature requests down here. Looking forward to work with you!
I will update the readme here in the following days to provide you with the latest changes.

~ Marius

### CODE REVIEW

**Comment by guiiamorim** [comment]
Hi @DeveloperMarius,

I looked at the changes you have made in the code under [v5-development-php8](https://github.com/DeveloperMarius/simple-php-router/tree/v5-development-php8) and made some of my own.

As I said on the other PR, I missed a method for filtering out fields that I didn't want in the request, so I implemented that. I also made some changes on some rules and replaced some functions that were there for support to other versions of PHP.

I would like to make a PR but it gives me permission denied. It's possible to give me permission or I'll have to continue working within a fork of your fork?

As soon as I can upload my work and we can discuss it, I would also like to discuss some rules that I think we need to tweak a bit.

**Comment by DeveloperMarius** [comment]
Hey,

sounds great 👍🏻.
Sorry, I had no time to write the documentation, but will look into it this weekend.
Because we are working on the fork you need to continue working with the fork of my fork. From the perspective of git, this fork is the main repository.

Looking forward to your PR.

~ Marius

**Comment by riku22** [comment]
Hello.

I did not know if this is the appropriate place to ask this question.
I am using this library for my main project.
However, the main repository has not been updated recently and, in particular, I get warnings and some parts do not work properly in PHP8 and later.
So, would you consider registering v5.0.0.0 to packagist so that it can be installed with composer?
It would be best to have them merged into the main repository.

Sincerely.

**Comment by DeveloperMarius** [comment]
Hello,

you can already add this router version using composer:
composer.json
```
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/developermarius/simple-php-router"
        },
        {
            "type": "composer",
            "url": "https://packagist.org"
        }
],
"require": {
  "pecee/simple-router": "dev-v5-development-php8"
}
```

**Comment by riku22** [comment]
Hello.

I have successfully installed it using the method you advised.
Thank you very much.

Sincerely.

**Comment by riku22** [comment]
hello.

I don't know if I can ask a question here, but let me ask you one.

I'd like to make the route strictly judge whether there is a trailing slash or not, is there any way?
For example, I want to treat `/page1` and `/page1/` as separate pages.
Both are currently on the same page.
By the way, the above specification seems to be the default in other frameworks, Slim, and it seems that they are treated as separate pages.
If there is any way, I would appreciate any advice.

Best regards.

**Comment by DeveloperMarius** [comment]
Hey @riku22,

I have to look deeper into that.
Sorry @all that I had no time to write the README and other stuff. I had too much work to do. I hope I will get into that in the comming weeks.
Thank you.

~ Marius

**Comment by DeveloperMarius** [comment]
Merged with master

**Pull request closed without merging**
